### ISSUE TITLE
可以给出详细的编译过程命令吗

### ISSUE THREAD

**Issue by aweewa** [xxxxnnxxxx/ruport#1]
编译时各种报错
root@ubuntu:~/ruport# make
  MKDIR    .output
  CC       .output/utils.o
  CC       .output/template.o
  CC       .output/log.o
cc -g -Wall -Wno-implicit-function-declaration -Wno-unused-function -Wno-unused-but-set-variable   -c -o utils.o utils.c
  MKDIR    .output/libbpf
  LIB      libbpf.a
make[1]: Entering directory '/root/ruport/libbpf/src'
  MKDIR    /root/ruport/.output//libbpf/staticobjs
  CC       /root/ruport/.output//libbpf/staticobjs/bpf.o
  CC       /root/ruport/.output//libbpf/staticobjs/btf.o
  CC       /root/ruport/.output//libbpf/staticobjs/libbpf.o
  CC       /root/ruport/.output//libbpf/staticobjs/libbpf_errno.o
  CC       /root/ruport/.output//libbpf/staticobjs/netlink.o
  CC       /root/ruport/.output//libbpf/staticobjs/nlattr.o
  CC       /root/ruport/.output//libbpf/staticobjs/str_error.o
  CC       /root/ruport/.output//libbpf/staticobjs/libbpf_probes.o
  CC       /root/ruport/.output//libbpf/staticobjs/bpf_prog_linfo.o
  CC       /root/ruport/.output//libbpf/staticobjs/xsk.o
  CC       /root/ruport/.output//libbpf/staticobjs/btf_dump.o
  CC       /root/ruport/.output//libbpf/staticobjs/hashmap.o
  CC       /root/ruport/.output//libbpf/staticobjs/ringbuf.o
  CC       /root/ruport/.output//libbpf/staticobjs/strset.o
  CC       /root/ruport/.output//libbpf/staticobjs/linker.o
  CC       /root/ruport/.output//libbpf/staticobjs/gen_loader.o
  CC       /root/ruport/.output//libbpf/staticobjs/relo_core.o
  AR       /root/ruport/.output//libbpf/libbpf.a
  INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h xsk.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h
  INSTALL  /root/ruport/.output//libbpf/libbpf.pc
  INSTALL  /root/ruport/.output//libbpf/libbpf.a
make[1]: Leaving directory '/root/ruport/libbpf/src'
  BPF      .output/ruport.bpf.o
  MKDIR    bpftool/
  BPFTOOL  bpftool/bpftool
make[1]: Entering directory '/root/ruport/bpftool/src'
...                        libbfd: [ OFF ]
...        disassembler-four-args: [ OFF ]
...                          zlib: [ on  ]
...                        libcap: [ OFF ]
...               clang-bpf-co-re: [ OFF ]
  MKDIR    /root/ruport/.output/bpftool//libbpf/
make[2]: Entering directory '/root/ruport/bpftool/libbpf/src'
  MKDIR    /root/ruport/.output/bpftool//libbpf/staticobjs
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/bpf.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/btf.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/libbpf.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/libbpf_errno.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/netlink.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/nlattr.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/str_error.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/libbpf_probes.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/bpf_prog_linfo.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/xsk.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/btf_dump.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/hashmap.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/ringbuf.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/strset.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/linker.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/gen_loader.o
  CC       /root/ruport/.output/bpftool//libbpf/staticobjs/relo_core.o
  AR       /root/ruport/.output/bpftool//libbpf/libbpf.a
  INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h xsk.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h
make[2]: Leaving directory '/root/ruport/bpftool/libbpf/src'
  MKDIR    /root/ruport/.output/bpftool//libbpf//include/bpf
  INSTALL  /root/ruport/.output/bpftool//libbpf//include/bpf/hashmap.h
  INSTALL  /root/ruport/.output/bpftool//libbpf//include/bpf/nlattr.h
  CC       /root/ruport/.output/bpftool/map_perf_ring.o
  CC       /root/ruport/.output/bpftool/xlated_dumper.o
  CC       /root/ruport/.output/bpftool/iter.o
  CC       /root/ruport/.output/bpftool/btf.o
  CC       /root/ruport/.output/bpftool/tracelog.o
  CC       /root/ruport/.output/bpftool/link.o
  CC       /root/ruport/.output/bpftool/perf.o
  CC       /root/ruport/.output/bpftool/prog.o
  CC       /root/ruport/.output/bpftool/btf_dumper.o
  CC       /root/ruport/.output/bpftool/net.o
  CC       /root/ruport/.output/bpftool/struct_ops.o
  CC       /root/ruport/.output/bpftool/netlink_dumper.o
  CC       /root/ruport/.output/bpftool/common.o
  CC       /root/ruport/.output/bpftool/cgroup.o
  CC       /root/ruport/.output/bpftool/gen.o
  CC       /root/ruport/.output/bpftool/main.o
  CC       /root/ruport/.output/bpftool/json_writer.o
  CC       /root/ruport/.output/bpftool/cfg.o
  CC       /root/ruport/.output/bpftool/map.o
  CC       /root/ruport/.output/bpftool/pids.o
  CC       /root/ruport/.output/bpftool/feature.o
  CC       /root/ruport/.output/bpftool/disasm.o
  LINK     /root/ruport/.output/bpftool/bpftool
make[1]: Leaving directory '/root/ruport/bpftool/src'
  GEN-SKEL .output/ruport.skel.h
libbpf: sec '.reltp/syscalls/sys_exit_getdents64': corrupted symbol #28 pointing to invalid section #65522 for relo #6
Error: failed to open BPF object file: BPF object format invalid
make: *** [Makefile:93: .output/ruport.skel.h] Error 95
make: *** Deleting file '.output/ruport.skel.h'

**Comment by xxxxnnxxxx** [comment]
系统环境是什么？

**Comment by xxxxnnxxxx** [comment]
你先 make cleanall 清理一下，然后再 make 编译
